title: camwuff
description: "A personal website for camwuff."
permalink: /post/:year/:month/:day/:title
hostname: "camwuff.com"

defaults:
  -
    scope:
      path: "node_modules/**"
    values:
      sitemap: false

include: 
  - .nojekyll

markdown: kramdown

plugins:
  - jekyll-node-module

node_modules:
  modules_dir: node_modules
  copy:
  - source: .
    target: node_modules

sass:
  load_paths:
    - _sass
    - node_modules
